2014/03/12 11:18:52 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/12 11:19:32 MainThread __main__ INFO starting application
2014/03/12 18:39:04 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/12 18:39:45 MainThread __main__ INFO starting application
2014/03/12 18:43:01 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/12 18:43:59 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/12 18:44:40 MainThread __main__ INFO starting application
2014/03/12 18:55:14 MainThread experiments WARNING No default settings.xml found.
2014/03/12 18:55:16 MainThread __main__ INFO starting application
2014/03/12 18:55:27 MainThread experiments WARNING No default settings.xml found.
2014/03/12 18:55:29 MainThread __main__ INFO starting application
2014/03/16 18:26:37 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/16 18:27:18 MainThread __main__ INFO starting application
2014/03/16 18:38:50 MainThread cs_evaluate WARNING evaluating property script, HSDIO script that says what waveforms to generate, script script1\ncompressedGenerate MOT_Loading\ncompressedGenerate PGC_1\ncompressedGenerate MOT_drop\ncompressedGenerate PreReadout\ncompressedGenerate Readout\ncompressedGenerate Camera_delay\ncompressedGenerate Readout\nend script'
Could not eval string: script script1\ncompressedGenerate MOT_Loading\ncompressedGenerate PGC_1\ncompressedGenerate MOT_drop\ncompressedGenerate PreReadout\ncompressedGenerate Readout\ncompressedGenerate Camera_delay\ncompressedGenerate Readout\nend script'
invalid syntax (<string>, line 1)Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1
    script script1\ncompressedGenerate MOT_Loading\ncompressedGenerate PGC_1\ncompressedGenerate MOT_drop\ncompressedGenerate PreReadout\ncompressedGenerate Readout\ncompressedGenerate Camera_delay\ncompressedGenerate Readout\nend script'
                 ^
SyntaxError: invalid syntax


2014/03/16 18:38:51 MainThread cs_evaluate WARNING evaluating property script, HSDIO script that says what waveforms to generate, '''script script1\ncompressedGenerate MOT_Loading\ncompressedGenerate PGC_1\ncompressedGenerate MOT_drop\ncompressedGenerate PreReadout\ncompressedGenerate Readout\ncompressedGenerate Camera_delay\ncompressedGenerate Readout\nend script'
Could not eval string: '''script script1\ncompressedGenerate MOT_Loading\ncompressedGenerate PGC_1\ncompressedGenerate MOT_drop\ncompressedGenerate PreReadout\ncompressedGenerate Readout\ncompressedGenerate Camera_delay\ncompressedGenerate Readout\nend script'
EOF while scanning triple-quoted string literal (<string>, line 1)Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1
    '''script script1\ncompressedGenerate MOT_Loading\ncompressedGenerate PGC_1\ncompressedGenerate MOT_drop\ncompressedGenerate PreReadout\ncompressedGenerate Readout\ncompressedGenerate Camera_delay\ncompressedGenerate Readout\nend script'
                                                                                                                                                                                                                                                ^
SyntaxError: EOF while scanning triple-quoted string literal


2014/03/16 18:38:53 MainThread cs_evaluate WARNING evaluating property script, HSDIO script that says what waveforms to generate, '''script script1\ncompressedGenerate MOT_Loading\ncompressedGenerate PGC_1\ncompressedGenerate MOT_drop\ncompressedGenerate PreReadout\ncompressedGenerate Readout\ncompressedGenerate Camera_delay\ncompressedGenerate Readout\nend script
Could not eval string: '''script script1\ncompressedGenerate MOT_Loading\ncompressedGenerate PGC_1\ncompressedGenerate MOT_drop\ncompressedGenerate PreReadout\ncompressedGenerate Readout\ncompressedGenerate Camera_delay\ncompressedGenerate Readout\nend script
EOF while scanning triple-quoted string literal (<string>, line 1)Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1
    '''script script1\ncompressedGenerate MOT_Loading\ncompressedGenerate PGC_1\ncompressedGenerate MOT_drop\ncompressedGenerate PreReadout\ncompressedGenerate Readout\ncompressedGenerate Camera_delay\ncompressedGenerate Readout\nend script
                                                                                                                                                                                                                                               ^
SyntaxError: EOF while scanning triple-quoted string literal


2014/03/16 18:40:56 MainThread LabView DEBUG LabView.open() opening sock
2014/03/16 18:40:56 MainThread LabView DEBUG LabView.open() sock opened
2014/03/16 18:40:59 MainThread LabView DEBUG debug LabView.open() closing sock
2014/03/16 18:40:59 MainThread LabView DEBUG LabView.open() opening sock
2014/03/16 18:40:59 MainThread LabView DEBUG LabView.open() sock opened
2014/03/16 18:47:15 MainThread cs_evaluate WARNING evaluating property enable, enable HSDIO output, True
Could not eval string: F
name 'F' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'F' is not defined


2014/03/16 18:47:15 MainThread cs_evaluate WARNING evaluating property enable, enable HSDIO output, True
Could not eval string: Fa
name 'Fa' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Fa' is not defined


2014/03/16 18:47:15 MainThread cs_evaluate WARNING evaluating property enable, enable HSDIO output, True
Could not eval string: Fal
name 'Fal' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Fal' is not defined


2014/03/16 18:47:15 MainThread cs_evaluate WARNING evaluating property enable, enable HSDIO output, True
Could not eval string: Fals
name 'Fals' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Fals' is not defined


2014/03/16 18:47:22 MainThread cs_evaluate WARNING evaluating property enable, enable HSDIO output, False
Could not eval string: T
name 'T' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'T' is not defined


2014/03/16 18:47:22 MainThread cs_evaluate WARNING evaluating property enable, enable HSDIO output, False
Could not eval string: Tr
name 'Tr' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Tr' is not defined


2014/03/16 18:47:22 MainThread cs_evaluate WARNING evaluating property enable, enable HSDIO output, False
Could not eval string: Tru
name 'Tru' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Tru' is not defined


2014/03/16 18:47:25 MainThread cs_evaluate WARNING evaluating property waitForStartTrigger, HSDIO wait for start trigger, True
Could not eval string: F
name 'F' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'F' is not defined


2014/03/16 18:47:25 MainThread cs_evaluate WARNING evaluating property waitForStartTrigger, HSDIO wait for start trigger, True
Could not eval string: Fa
name 'Fa' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Fa' is not defined


2014/03/16 18:47:25 MainThread cs_evaluate WARNING evaluating property waitForStartTrigger, HSDIO wait for start trigger, True
Could not eval string: Fal
name 'Fal' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Fal' is not defined


2014/03/16 18:47:26 MainThread cs_evaluate WARNING evaluating property waitForStartTrigger, HSDIO wait for start trigger, True
Could not eval string: Fals
name 'Fals' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Fals' is not defined


2014/03/16 18:50:14 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/16 18:50:54 MainThread __main__ INFO starting application
2014/03/16 19:14:03 MainThread LabView DEBUG LabView.open() opening sock
2014/03/16 19:14:03 MainThread LabView DEBUG LabView.open() sock opened
2014/03/16 19:14:09 MainThread LabView WARNING LabView instrument should be initialized already, but is not, in LabView.update()
2014/03/16 19:14:57 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/16 19:15:38 MainThread __main__ INFO starting application
2014/03/16 19:16:26 MainThread LabView DEBUG LabView.open() opening sock
2014/03/16 19:16:26 MainThread LabView DEBUG LabView.open() sock opened
2014/03/16 19:17:29 Thread-1 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/16 19:28:00 MainThread analysis WARNING Exception trying to plot measurement 0, shot 2, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 19:28:10 MainThread analysis WARNING Exception trying to plot measurement 20, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 19:28:10 MainThread analysis WARNING Exception trying to plot measurement 21, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 19:28:11 MainThread analysis WARNING Exception trying to plot measurement 20, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 19:30:46 MainThread analysis WARNING Exception trying to plot measurement 0, shot 2, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:15:15 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/16 20:15:17 MainThread instrument_property WARNING Evaluating AnalogOutput in LabView.properties.
unbound method set_axis() must be called with NullFormatter instance as first argument (got XAxis instance instead)Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\instrument_property.py", line 42, in evaluate
    o.evaluate() #evaluate it
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 163, in evaluate
    self.update_plot()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 143, in update_plot
    self.drawMPL()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 132, in drawMPL
    ax.xaxis.set_major_formatter(NullFormatter)
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\axis.py", line 1441, in set_major_formatter
    formatter.set_axis(self)
TypeError: unbound method set_axis() must be called with NullFormatter instance as first argument (got XAxis instance instead)


2014/03/16 20:15:17 MainThread experiments WARNING PauseError
2014/03/16 20:15:55 MainThread __main__ INFO starting application
2014/03/16 20:18:18 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/16 20:18:19 MainThread instrument_property WARNING Evaluating AnalogOutput in LabView.properties.
unbound method set_axis() must be called with NullFormatter instance as first argument (got XAxis instance instead)Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\instrument_property.py", line 42, in evaluate
    o.evaluate() #evaluate it
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 164, in evaluate
    self.update_plot()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 144, in update_plot
    self.drawMPL()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 132, in drawMPL
    ax.xaxis.set_major_formatter(NullFormatter)
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\axis.py", line 1441, in set_major_formatter
    formatter.set_axis(self)
TypeError: unbound method set_axis() must be called with NullFormatter instance as first argument (got XAxis instance instead)


2014/03/16 20:18:19 MainThread experiments WARNING PauseError
2014/03/16 20:18:54 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/16 20:19:34 MainThread __main__ INFO starting application
2014/03/16 20:40:36 MainThread LabView WARNING LabView instrument should be initialized already, but is not, in LabView.update()
2014/03/16 20:40:47 MainThread LabView DEBUG LabView.open() opening sock
2014/03/16 20:40:47 MainThread LabView DEBUG LabView.open() sock opened
2014/03/16 20:40:51 MainThread LabView WARNING LabView instrument should be initialized already, but is not, in LabView.update()
2014/03/16 20:41:04 MainThread LabView DEBUG debug LabView.open() closing sock
2014/03/16 20:41:04 MainThread LabView DEBUG LabView.open() opening sock
2014/03/16 20:41:04 MainThread LabView DEBUG LabView.open() sock opened
2014/03/16 20:45:12 Thread-1 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/16 20:45:17 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:45:21 MainThread analysis WARNING Exception trying to plot measurement 1, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:45:45 Thread-2 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/16 20:45:57 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:46:00 MainThread analysis WARNING Exception trying to plot measurement 2, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:46:13 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:46:50 Thread-3 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/16 20:46:54 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:47:00 MainThread analysis WARNING Exception trying to plot measurement 3, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:47:23 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:47:47 Thread-4 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/16 20:48:33 Thread-5 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/16 20:48:45 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:48:53 MainThread analysis WARNING Exception trying to plot measurement 20, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:51:36 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/16 20:53:35 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/16 20:54:05 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/16 20:54:46 MainThread __main__ INFO starting application
2014/03/16 20:55:18 MainThread LabView DEBUG LabView.open() opening sock
2014/03/16 20:55:18 MainThread LabView DEBUG LabView.open() sock opened
2014/03/16 20:55:49 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:55:59 Thread-1 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/16 20:56:09 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:56:12 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:56:51 MainThread analysis WARNING Exception trying to plot measurement 12, shot 2, in analysis.ShotsBrowserAnalysis.load()

2014/03/16 20:56:59 MainThread analysis WARNING Exception trying to plot measurement 20, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/17 08:43:44 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/17 08:44:25 MainThread __main__ INFO starting application
2014/03/18 18:44:02 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/18 18:44:43 MainThread __main__ INFO starting application
2014/03/18 18:45:08 MainThread instrument_property WARNING While trying toHDF5() on list item channel in ListProp.toHDF5() in state.
unable to create group (Symbol table: Unable to initialize object)

2014/03/18 18:45:08 MainThread instrument_property WARNING While trying state.toHDF5() in Prop.toHDF5() in transition.


2014/03/18 18:45:08 MainThread instrument_property WARNING While trying toHDF5() on list item transition in ListProp.toHDF5() in sequence.


2014/03/18 18:45:08 MainThread instrument_property WARNING While trying sequence.toHDF5() in Prop.toHDF5() in idle.


2014/03/18 18:45:08 MainThread instrument_property WARNING While trying toHDF5() on list item idle in ListProp.toHDF5() in waveforms.


2014/03/18 18:45:08 MainThread instrument_property WARNING While trying waveforms.toHDF5() in Prop.toHDF5() in HSDIO.


2014/03/18 18:45:08 MainThread instrument_property WARNING While trying HSDIO.toHDF5() in Prop.toHDF5() in LabView.


2014/03/18 18:45:08 MainThread instrument_property WARNING While trying LabView.toHDF5() in Prop.toHDF5() in experiment.


2014/03/18 18:53:27 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/18 18:54:08 MainThread __main__ INFO starting application
2014/03/18 18:56:40 MainThread instrument_property WARNING While trying toHDF5() on list item channel1 in ListProp.toHDF5() in state.
unable to create group (Symbol table: Unable to initialize object)

2014/03/18 18:56:40 MainThread instrument_property WARNING While trying state.toHDF5() in Prop.toHDF5() in transition.


2014/03/18 18:56:40 MainThread instrument_property WARNING While trying toHDF5() on list item transition0 in ListProp.toHDF5() in sequence.


2014/03/18 18:56:40 MainThread instrument_property WARNING While trying sequence.toHDF5() in Prop.toHDF5() in idle.


2014/03/18 18:56:40 MainThread instrument_property WARNING While trying toHDF5() on list item element0 in ListProp.toHDF5() in waveforms.


2014/03/18 18:56:40 MainThread instrument_property WARNING While trying waveforms.toHDF5() in Prop.toHDF5() in HSDIO.


2014/03/18 18:56:40 MainThread instrument_property WARNING While trying HSDIO.toHDF5() in Prop.toHDF5() in LabView.


2014/03/18 18:56:40 MainThread instrument_property WARNING While trying LabView.toHDF5() in Prop.toHDF5() in experiment.


2014/03/18 18:58:50 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/18 18:59:30 MainThread __main__ INFO starting application
2014/03/18 19:17:56 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/18 19:18:37 MainThread __main__ INFO starting application
2014/03/19 16:54:49 MainThread instrument_property WARNING Exception in EvalProp.evaluate() in totalAOTime.
description: 
function: 5.0
local variable 'ax' referenced before assignment

2014/03/19 16:54:49 MainThread instrument_property WARNING Exception in EvalProp.evaluate() in units.
description: equations entered in ms
function: .001
local variable 'ax' referenced before assignment

2014/03/19 16:54:49 MainThread instrument_property WARNING Exception in EvalProp.evaluate() in clockRate.
description: 
function: 20*kilo
local variable 'ax' referenced before assignment

2014/03/19 16:54:49 MainThread instrument_property WARNING Exception in EvalProp.evaluate() in totalAOTime.
description: 5 ms total
function: total_AO_time
local variable 'ax' referenced before assignment

2014/03/19 16:54:49 MainThread instrument_property WARNING in equations in ListProp.fromXML() for xml tag: equations.
local variable 'ax' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\instrument_property.py", line 632, in fromXML
    self.listProperty=[self.listElementType(self.listElementName+str(i),self.experiment,**self.listElementKwargs).fromXML(child) for i,child in enumerate(xmlNode)]
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 33, in __init__
    super(AOEquation,self).__init__(name,experiment,function='0*t')
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\instrument_property.py", line 322, in __init__
    super(EvalProp,self).__init__(name,experiment,description)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\instrument_property.py", line 27, in __init__
    self.description=description #English language description, including units and hints about possible values
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 38, in _observe_description
    self.AO.update_plot()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 155, in update_plot
    self.drawMPL()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 140, in drawMPL
    ylim=ax.get_ylim()
UnboundLocalError: local variable 'ax' referenced before assignment


2014/03/19 16:54:49 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/19 16:54:50 MainThread instrument_property WARNING Evaluating AnalogOutput in LabView.properties.
local variable 'ax' referenced before assignmentTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\instrument_property.py", line 42, in evaluate
    o.evaluate() #evaluate it
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 175, in evaluate
    self.update_plot()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 155, in update_plot
    self.drawMPL()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\AnalogOutput.py", line 140, in drawMPL
    ylim=ax.get_ylim()
UnboundLocalError: local variable 'ax' referenced before assignment


2014/03/19 16:54:50 MainThread experiments WARNING PauseError
2014/03/19 16:55:33 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/19 16:56:13 MainThread __main__ INFO starting application
2014/03/19 16:57:30 MainThread instrument_property WARNING While trying independentVariables.toHDF5() in Prop.toHDF5() in experiment.
global name 'my_node' is not defined

2014/03/19 17:02:17 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/19 17:02:58 MainThread __main__ INFO starting application
2014/03/19 17:03:56 MainThread instrument_property WARNING While trying toHDF5() on list item channel in ListProp.toHDF5() in state.
unable to create group (Symbol table: Unable to initialize object)

2014/03/19 17:03:56 MainThread instrument_property WARNING While trying state.toHDF5() in Prop.toHDF5() in transition.


2014/03/19 17:03:56 MainThread instrument_property WARNING While trying sequence.toHDF5() in Prop.toHDF5() in idle.


2014/03/19 17:03:56 MainThread instrument_property WARNING While trying waveforms.toHDF5() in Prop.toHDF5() in HSDIO.


2014/03/19 17:03:56 MainThread instrument_property WARNING While trying HSDIO.toHDF5() in Prop.toHDF5() in LabView.


2014/03/19 17:03:56 MainThread instrument_property WARNING While trying LabView.toHDF5() in Prop.toHDF5() in experiment.


2014/03/19 17:05:36 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/19 17:06:16 MainThread __main__ INFO starting application
2014/03/20 10:57:47 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/20 10:58:27 MainThread __main__ INFO starting application
2014/03/21 10:34:08 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/21 10:34:48 MainThread __main__ INFO starting application
2014/03/21 12:40:52 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/21 12:41:31 MainThread __main__ INFO starting application
2014/03/21 20:13:23 MainThread experiments WARNING Index=1 out of range for independent variable independentVariable0. Setting independentVariable0.index=0

2014/03/21 20:13:23 MainThread cs_evaluate WARNING evaluating variables report
Could not eval string: '''a is %(a)s.
The speed of light is %(c0)d
but some call it %(c0)e
microwave raman time=%(microwave_Raman_time)e
'''%locals()
'a'Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 5, in <module>
KeyError: 'a'


2014/03/21 20:17:37 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/21 20:18:17 MainThread __main__ INFO starting application
2014/03/22 16:04:53 MainThread experiments WARNING Index=1 out of range for independent variable independentVariable0. Setting independentVariable0.index=0

2014/03/22 16:04:53 MainThread cs_evaluate WARNING evaluating variables report
Could not eval string: '''a is %(a)s.
The speed of light is %(c0)d
but some call it %(c0)e
microwave raman time=%(microwave_Raman_time)e
'''%locals()
'a'Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 5, in <module>
KeyError: 'a'


2014/03/22 18:41:10 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/22 18:41:51 MainThread __main__ INFO starting application
2014/03/22 18:43:26 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/22 18:43:26 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/22 18:43:26 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 18:43:26 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 18:43:28 Thread-1 LabView WARNING LabView error.  Log:
2014-03-22 18:43:48 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/22 18:43:30 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 18:43:30 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 18:43:32 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/22 18:46:36 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/22 18:47:16 MainThread __main__ INFO starting application
2014/03/22 19:00:57 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/22 19:00:57 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/22 19:00:57 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:00:57 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:00:58 Thread-1 LabView WARNING LabView error.  Log:
2014-03-22 19:01:19 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/22 19:01:00 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:01:00 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:01:01 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/22 19:03:35 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/22 19:04:15 MainThread __main__ INFO starting application
2014/03/22 19:15:00 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/22 19:15:00 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/22 19:15:00 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:15:00 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:15:01 Thread-1 LabView WARNING LabView error.  Log:
2014-03-22 19:15:21 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/22 19:15:03 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:15:03 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:15:04 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/22 19:15:44 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/22 19:16:25 MainThread __main__ INFO starting application
2014/03/22 19:16:38 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/22 19:16:38 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/22 19:16:38 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:16:38 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:16:39 Thread-1 LabView WARNING LabView error.  Log:
2014-03-22 19:16:59 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/22 19:16:41 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:16:41 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:16:42 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/22 19:25:52 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/22 19:26:32 MainThread __main__ INFO starting application
2014/03/22 19:47:37 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/22 19:47:37 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/22 19:47:37 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:47:37 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:47:40 Thread-1 LabView WARNING LabView error.  Log:
2014-03-22 19:48:00 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.

2014-03-22 19:48:00 DAQmx Stop Task.vi:3590004Warning 200010 occurred at DAQmx Stop Task.vi:3590004

Possible reason(s):

Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.
Call chain:
handle_errors.vi Analog_Output.lvclass:stop.vi Experiment.lvclass:stop_tasks.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/22 19:47:42 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:47:42 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:47:43 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/22 19:49:01 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/22 19:49:42 MainThread __main__ INFO starting application
2014/03/22 19:51:44 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/22 19:51:44 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/22 19:51:44 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:51:44 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:51:46 Thread-1 LabView WARNING LabView error.  Log:
2014-03-22 19:52:06 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.

2014-03-22 19:52:06 DAQmx Stop Task.vi:3590004Warning 200010 occurred at DAQmx Stop Task.vi:3590004

Possible reason(s):

Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.
Call chain:
handle_errors.vi Analog_Output.lvclass:stop.vi Experiment.lvclass:stop_tasks.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/22 19:51:48 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/22 19:51:48 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/22 19:51:50 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 14:24:22 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 14:25:03 MainThread __main__ INFO starting application
2014/03/23 14:26:41 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 14:26:41 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 14:26:41 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/23 14:26:41 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/23 14:26:44 Thread-1 LabView WARNING LabView error.  Log:
2014-03-23 14:27:07 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.

2014-03-23 14:27:07 DAQmx Stop Task.vi:3590005Warning 200010 occurred at DAQmx Stop Task.vi:3590005

Possible reason(s):

Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.
Call chain:
handle_errors.vi Analog_Output.lvclass:stop.vi Experiment.lvclass:stop_tasks.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/23 14:26:46 Thread-1 HSDIO WARNING HSDIO script says:   compressedGenerate MOT_Loading, but waveform MOT_Loading does not exist.
2014/03/23 14:26:46 Thread-1 instrument_property WARNING In Prop.HardwareProtocol() for class LabView while trying HSDIO.toHardware.


2014/03/23 14:26:48 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 14:32:19 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 14:32:59 MainThread __main__ INFO starting application
2014/03/23 14:35:14 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 14:35:14 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 14:35:16 Thread-1 LabView WARNING LabView error.  Log:
2014-03-23 14:35:39 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.

2014-03-23 14:35:39 DAQmx Stop Task.vi:3590005Warning 200010 occurred at DAQmx Stop Task.vi:3590005

Possible reason(s):

Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.
Call chain:
handle_errors.vi Analog_Output.lvclass:stop.vi Experiment.lvclass:stop_tasks.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/23 14:35:20 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 14:50:13 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 14:50:54 MainThread __main__ INFO starting application
2014/03/23 14:55:54 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 14:55:54 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 14:55:56 Thread-1 LabView WARNING LabView error.  Log:
2014-03-23 14:56:19 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.

2014-03-23 14:56:19 DAQmx Stop Task.vi:3590005Warning 200010 occurred at DAQmx Stop Task.vi:3590005

Possible reason(s):

Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.
Call chain:
handle_errors.vi Analog_Output.lvclass:stop.vi Experiment.lvclass:stop_tasks.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/23 14:56:00 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 14:59:01 MainThread LabView DEBUG debug LabView.open() closing sock
2014/03/23 14:59:01 MainThread LabView DEBUG LabView.open() opening sock
2014/03/23 14:59:01 MainThread LabView DEBUG LabView.open() sock opened
2014/03/23 14:59:05 Thread-2 experiments INFO Current status is paused after error. Cannot reset experiment unless status is idle.  Try halting first.
2014/03/23 14:59:08 Thread-2 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 14:59:50 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 15:00:31 MainThread __main__ INFO starting application
2014/03/23 15:02:03 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 15:02:44 MainThread __main__ INFO starting application
2014/03/23 15:04:56 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 15:04:56 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 15:04:58 Thread-1 LabView WARNING LabView error.  Log:
2014-03-23 15:05:21 Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.Error 0 occurred at Warning:  The measurement ended due to the master timeout, before all output tasks were complete.  Consider increasing the timeout.

Possible reason(s):

LabVIEW:  Error connecting to GPIB driver or device.
=========================
NI-488:  Error connecting to driver or device.
=========================
NI-845x:  The operation completed successfully.
=========================
VISA:  (Hex 0x0) Operation completed successfully.
Call chain:
handle_errors.vi Experiment.lvclass:check_timeout.vi Experiment.lvclass:isDone.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.

2014-03-23 15:05:21 DAQmx Stop Task.vi:3590005Warning 200010 occurred at DAQmx Stop Task.vi:3590005

Possible reason(s):

Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.
Call chain:
handle_errors.vi Analog_Output.lvclass:stop.vi Experiment.lvclass:stop_tasks.vi Experiment.lvclass:measurement.vi Experiment.lvclass:parseXMLstring.vi Experiment.lvclass:server.vi

Error cleared. Exiting operation.


2014/03/23 15:05:02 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 591, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 15:11:16 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 15:11:57 MainThread __main__ INFO starting application
2014/03/23 15:13:39 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 15:13:39 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 15:13:53 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 15:14:03 Thread-1 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 15:21:00 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 15:21:41 MainThread __main__ INFO starting application
2014/03/23 15:22:08 Thread-1 experiments DEBUG Autosaving
2014/03/23 15:22:50 Thread-1 experiments DEBUG Done autosaving
2014/03/23 15:22:50 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 15:22:50 Thread-1 experiments DEBUG Autosave closed
2014/03/23 15:22:50 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 15:22:52 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 15:22:52 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 15:41:52 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 15:42:33 MainThread __main__ INFO starting application
2014/03/23 15:46:14 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 15:46:55 MainThread __main__ INFO starting application
2014/03/23 15:48:54 Thread-1 experiments DEBUG Autosaving
2014/03/23 15:48:54 Thread-1 experiments DEBUG Done autosaving
2014/03/23 15:48:54 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 15:48:54 Thread-1 experiments DEBUG Autosave closed
2014/03/23 15:48:54 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 15:48:56 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 15:48:56 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 15:49:17 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 15:49:21 Thread-1 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 15:49:30 MainThread analysis WARNING Exception trying to plot measurement 11, shot 2, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 15:49:35 MainThread analysis WARNING Exception trying to plot measurement 20, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 15:49:37 MainThread analysis WARNING Exception trying to plot measurement 20, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 15:49:56 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 15:50:36 Thread-2 experiments DEBUG Autosaving
2014/03/23 15:50:36 Thread-2 experiments DEBUG Done autosaving
2014/03/23 15:50:36 Thread-2 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 15:50:36 Thread-2 experiments DEBUG Autosave closed
2014/03/23 15:50:36 Thread-2 experiments DEBUG Finished create_data_files()
2014/03/23 15:50:48 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 15:50:59 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 15:51:04 Thread-2 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 15:51:09 Thread-3 experiments DEBUG Autosaving
2014/03/23 15:51:09 Thread-3 experiments DEBUG Done autosaving
2014/03/23 15:51:09 Thread-3 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 15:51:09 Thread-3 experiments DEBUG Autosave closed
2014/03/23 15:51:09 Thread-3 experiments DEBUG Finished create_data_files()
2014/03/23 15:51:37 Thread-3 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 16:37:22 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 16:38:02 MainThread __main__ INFO starting application
2014/03/23 16:43:43 Thread-1 experiments DEBUG Autosaving
2014/03/23 16:43:43 Thread-1 experiments DEBUG Done autosaving
2014/03/23 16:43:43 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 16:43:43 Thread-1 experiments DEBUG Autosave closed
2014/03/23 16:43:43 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 16:43:46 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 16:43:46 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 16:44:09 Thread-1 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 16:45:05 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 16:45:43 Thread-2 experiments DEBUG Autosaving
2014/03/23 16:45:43 Thread-2 experiments DEBUG Done autosaving
2014/03/23 16:45:43 Thread-2 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 16:45:43 Thread-2 experiments DEBUG Autosave closed
2014/03/23 16:45:43 Thread-2 experiments DEBUG Finished create_data_files()
2014/03/23 16:45:49 Thread-2 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 16:45:52 MainThread analysis WARNING Exception trying to plot measurement 1, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 16:45:58 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 16:46:00 MainThread analysis WARNING Exception trying to plot measurement 1, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 16:57:01 Thread-3 experiments DEBUG Autosaving
2014/03/23 16:57:01 Thread-3 experiments DEBUG Done autosaving
2014/03/23 16:57:01 Thread-3 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 16:57:01 Thread-3 experiments DEBUG Autosave closed
2014/03/23 16:57:01 Thread-3 experiments DEBUG Finished create_data_files()
2014/03/23 16:57:06 Thread-3 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 16:57:37 Thread-4 experiments DEBUG Autosaving
2014/03/23 16:57:37 Thread-4 experiments DEBUG Done autosaving
2014/03/23 16:57:37 Thread-4 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 16:57:37 Thread-4 experiments DEBUG Autosave closed
2014/03/23 16:57:37 Thread-4 experiments DEBUG Finished create_data_files()
2014/03/23 16:57:42 Thread-4 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 16:58:00 Thread-5 experiments DEBUG Autosaving
2014/03/23 16:58:00 Thread-5 experiments DEBUG Done autosaving
2014/03/23 16:58:00 Thread-5 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 16:58:00 Thread-5 experiments DEBUG Autosave closed
2014/03/23 16:58:00 Thread-5 experiments DEBUG Finished create_data_files()
2014/03/23 16:58:05 Thread-5 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 16:58:15 Thread-6 experiments DEBUG Autosaving
2014/03/23 16:58:15 Thread-6 experiments DEBUG Done autosaving
2014/03/23 16:58:15 Thread-6 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 16:58:15 Thread-6 experiments DEBUG Autosave closed
2014/03/23 16:58:15 Thread-6 experiments DEBUG Finished create_data_files()
2014/03/23 16:59:56 Thread-6 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 17:00:39 Thread-7 experiments DEBUG Autosaving
2014/03/23 17:00:39 Thread-7 experiments DEBUG Done autosaving
2014/03/23 17:00:39 Thread-7 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 17:00:39 Thread-7 experiments DEBUG Autosave closed
2014/03/23 17:00:39 Thread-7 experiments DEBUG Finished create_data_files()
2014/03/23 17:02:24 Thread-7 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 17:07:05 Thread-8 experiments DEBUG Autosaving
2014/03/23 17:07:05 Thread-8 experiments DEBUG Done autosaving
2014/03/23 17:07:05 Thread-8 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 17:07:05 Thread-8 experiments DEBUG Autosave closed
2014/03/23 17:07:05 Thread-8 experiments DEBUG Finished create_data_files()
2014/03/23 17:07:23 MainThread analysis WARNING Exception trying to plot measurement 11, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 17:07:23 MainThread analysis WARNING Exception trying to plot measurement 12, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 17:09:10 Thread-8 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 17:13:45 Thread-9 experiments DEBUG Autosaving
2014/03/23 17:13:45 Thread-9 experiments DEBUG Done autosaving
2014/03/23 17:13:45 Thread-9 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 17:13:45 Thread-9 experiments DEBUG Autosave closed
2014/03/23 17:13:45 Thread-9 experiments DEBUG Finished create_data_files()
2014/03/23 17:14:05 Thread-9 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 17:14:43 MainThread experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 17:15:24 MainThread __main__ INFO starting application
2014/03/23 17:16:26 Thread-1 experiments DEBUG Autosaving
2014/03/23 17:16:26 Thread-1 experiments DEBUG Done autosaving
2014/03/23 17:16:26 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 17:16:26 Thread-1 experiments DEBUG Autosave closed
2014/03/23 17:16:26 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 17:16:29 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 17:16:29 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 17:17:15 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 17:17:23 Thread-1 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 17:17:29 Thread-2 experiments DEBUG Autosaving
2014/03/23 17:17:29 Thread-2 experiments DEBUG Done autosaving
2014/03/23 17:17:29 Thread-2 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 17:17:29 Thread-2 experiments DEBUG Autosave closed
2014/03/23 17:17:29 Thread-2 experiments DEBUG Finished create_data_files()
2014/03/23 17:17:49 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 17:17:54 MainThread analysis WARNING Exception trying to plot measurement 0, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 17:18:01 Thread-2 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 17:21:22 MainThread __main__ INFO starting application
2014/03/23 17:21:35 Thread-1 experiments DEBUG Autosaving
2014/03/23 17:21:35 Thread-1 experiments DEBUG Done autosaving
2014/03/23 17:21:35 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 17:21:35 Thread-1 experiments DEBUG Autosave closed
2014/03/23 17:21:35 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 17:21:38 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 17:21:38 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 17:31:27 Thread-1 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 18:20:34 Thread-2 experiments DEBUG Autosaving
2014/03/23 18:20:34 Thread-2 experiments DEBUG Done autosaving
2014/03/23 18:20:34 Thread-2 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 18:20:34 Thread-2 experiments DEBUG Autosave closed
2014/03/23 18:20:34 Thread-2 experiments DEBUG Finished create_data_files()
2014/03/23 18:26:54 MainThread __main__ INFO starting application
2014/03/23 18:32:08 Thread-1 experiments DEBUG Autosaving
2014/03/23 18:32:08 Thread-1 experiments DEBUG Done autosaving
2014/03/23 18:32:08 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 18:32:08 Thread-1 experiments DEBUG Autosave closed
2014/03/23 18:32:08 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 18:32:11 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 18:32:11 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 18:32:59 Thread-1 experiments ERROR Exception during experiment:
"can't open attribute (Attribute: Can't open object)"
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 373, in go2
    self.measure()     #tell all instruments to do the experiment sequence and acquire data
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 452, in measure
    self.postMeasurement()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 631, in postMeasurement
    a=i.postMeasurement(self.measurementResults,self.iterationResults,self.hdf5)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\analysis.py", line 63, in postMeasurement
    return self.analyzeMeasurement(measurementResults,iterationResults,experimentResults)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\save2013style.py", line 66, in analyzeMeasurement
    self.savePNG(value.value,os.path.join(iterationPath,'Iteration'+str(iterationResults.attrs['iteration'])+'Measurement'+str(measurementResults.attrs['measurement'])+'Shot'+str(key)+'.png'))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\attrs.py", line 48, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5a.pyx", line 74, in h5py.h5a.open (h5py\h5a.c:2018)
KeyError: "can't open attribute (Attribute: Can't open object)"


2014/03/23 18:33:16 MainThread cs_evaluate WARNING evaluating property saveAsPNG, save pictures as PNG, False
Could not eval string: T
name 'T' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'T' is not defined


2014/03/23 18:33:16 MainThread cs_evaluate WARNING evaluating property saveAsPNG, save pictures as PNG, False
Could not eval string: Tr
name 'Tr' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Tr' is not defined


2014/03/23 18:33:16 MainThread cs_evaluate WARNING evaluating property saveAsPNG, save pictures as PNG, False
Could not eval string: Tru
name 'Tru' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Tru' is not defined


2014/03/23 18:33:26 Thread-2 experiments INFO Current status is paused after error. Cannot reset experiment unless status is idle.  Try halting first.
2014/03/23 18:33:32 Thread-2 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 373, in go2
    self.measure()     #tell all instruments to do the experiment sequence and acquire data
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 443, in measure
    self.measurementResults=self.hdf5.create_group('iterations/'+str(self.iteration)+'/measurements/'+str(self.measurement))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 18:33:37 Thread-3 experiments INFO Current status is paused after error. Cannot reset experiment unless status is idle.  Try halting first.
2014/03/23 18:33:44 Thread-3 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 373, in go2
    self.measure()     #tell all instruments to do the experiment sequence and acquire data
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 443, in measure
    self.measurementResults=self.hdf5.create_group('iterations/'+str(self.iteration)+'/measurements/'+str(self.measurement))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 18:33:52 Thread-4 experiments DEBUG Autosaving
2014/03/23 18:33:52 Thread-4 experiments DEBUG Done autosaving
2014/03/23 18:33:52 Thread-4 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 18:33:52 Thread-4 experiments DEBUG Autosave closed
2014/03/23 18:33:52 Thread-4 experiments DEBUG Finished create_data_files()
2014/03/23 18:39:01 MainThread __main__ INFO starting application
2014/03/23 18:39:47 MainThread cs_evaluate WARNING evaluating property saveAsPNG, save pictures as PNG, False
Could not eval string: T
name 'T' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'T' is not defined


2014/03/23 18:39:47 MainThread cs_evaluate WARNING evaluating property saveAsPNG, save pictures as PNG, False
Could not eval string: Tr
name 'Tr' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Tr' is not defined


2014/03/23 18:39:47 MainThread cs_evaluate WARNING evaluating property saveAsPNG, save pictures as PNG, False
Could not eval string: Tru
name 'Tru' is not definedTraceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\cs_evaluate.py", line 28, in evalWithDict
    return eval(string,globals()) #,varDict.copy()) #dict(numpyDict.items()+varDict.items())) #create a new dictionary so all numpy functions and everything defined in varDict is available as a global during evaluation
  File "<string>", line 1, in <module>
NameError: name 'Tru' is not defined


2014/03/23 18:46:19 MainThread __main__ INFO starting application
2014/03/23 18:47:31 Thread-1 experiments DEBUG Autosaving
2014/03/23 18:47:31 Thread-1 experiments DEBUG Done autosaving
2014/03/23 18:47:31 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 18:47:31 Thread-1 experiments DEBUG Autosave closed
2014/03/23 18:47:31 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 18:47:33 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 18:47:33 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 18:47:37 Thread-1 experiments ERROR Exception during experiment:
global name 'camera' is not defined
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 373, in go2
    self.measure()     #tell all instruments to do the experiment sequence and acquire data
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 450, in measure
    i.writeResults(self.measurementResults['data'])
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\LabView.py", line 157, in writeResults
    if hasattr(self,camera) and self.camera.savePNG:
NameError: global name 'camera' is not defined


2014/03/23 18:47:41 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 603, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 18:49:21 MainThread __main__ INFO starting application
2014/03/23 18:51:01 Thread-1 experiments DEBUG Autosaving
2014/03/23 18:51:01 Thread-1 experiments DEBUG Done autosaving
2014/03/23 18:51:01 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 18:51:01 Thread-1 experiments DEBUG Autosave closed
2014/03/23 18:51:01 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 18:51:04 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 18:51:04 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 18:51:07 Thread-1 experiments ERROR Exception during experiment:
'HamamatsuC9100_13' object has no attribute 'savePNG'
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 373, in go2
    self.measure()     #tell all instruments to do the experiment sequence and acquire data
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 450, in measure
    i.writeResults(self.measurementResults['data'])
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\LabView.py", line 157, in writeResults
    if hasattr(self,'camera') and self.camera.savePNG:
AttributeError: 'HamamatsuC9100_13' object has no attribute 'savePNG'


2014/03/23 18:51:12 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 603, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 18:53:13 MainThread __main__ INFO starting application
2014/03/23 18:53:21 Thread-1 experiments DEBUG Autosaving
2014/03/23 18:53:21 Thread-1 experiments DEBUG Done autosaving
2014/03/23 18:53:21 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 18:53:21 Thread-1 experiments DEBUG Autosave closed
2014/03/23 18:53:21 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 18:53:23 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 18:53:23 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 18:53:27 Thread-1 LabView WARNING problem saving PNG in LabView.writeResults()
'LabView' object has no attribute 'saveAsPNG'
2014/03/23 18:53:31 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 603, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 18:59:49 MainThread __main__ INFO starting application
2014/03/23 19:01:03 Thread-1 experiments DEBUG Autosaving
2014/03/23 19:01:03 Thread-1 experiments DEBUG Done autosaving
2014/03/23 19:01:03 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 19:01:03 Thread-1 experiments DEBUG Autosave closed
2014/03/23 19:01:03 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 19:01:05 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 19:01:05 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 19:01:09 Thread-1 experiments ERROR Exception during experiment:
"can't open attribute (Attribute: Can't open object)"
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 373, in go2
    self.measure()     #tell all instruments to do the experiment sequence and acquire data
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 452, in measure
    self.postMeasurement()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 631, in postMeasurement
    a=i.postMeasurement(self.measurementResults,self.iterationResults,self.hdf5)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\analysis.py", line 62, in postMeasurement
    return self.analyzeMeasurement(measurementResults,iterationResults,experimentResults)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\save2013style.py", line 66, in analyzeMeasurement
    self.savePNG(value.value,os.path.join(iterationPath,'Iteration'+str(iterationResults.attrs['iteration'])+'Measurement'+str(measurementResults.attrs['measurement'])+'Shot'+str(key)+'.png'))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\attrs.py", line 48, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5a.pyx", line 74, in h5py.h5a.open (h5py\h5a.c:2018)
KeyError: "can't open attribute (Attribute: Can't open object)"


2014/03/23 19:01:13 Thread-1 experiments ERROR Exception during experiment:
unable to create group (Symbol table: Unable to initialize object)
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 368, in go2
    self.create_hdf5_iteration()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 603, in create_hdf5_iteration
    self.iterationResults=self.hdf5.create_group('iterations/'+str(self.iteration))
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\h5py\_hl\group.py", line 41, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl)
  File "h5g.pyx", line 145, in h5py.h5g.create (h5py\h5g.c:2378)
ValueError: unable to create group (Symbol table: Unable to initialize object)


2014/03/23 19:04:53 MainThread __main__ INFO starting application
2014/03/23 19:04:57 Thread-1 experiments DEBUG Autosaving
2014/03/23 19:04:57 Thread-1 experiments DEBUG Done autosaving
2014/03/23 19:04:57 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 19:04:57 Thread-1 experiments DEBUG Autosave closed
2014/03/23 19:04:57 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 19:05:00 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 19:05:00 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 19:05:12 MainThread analysis WARNING Exception trying to plot measurement 5, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 19:05:12 MainThread analysis WARNING Exception trying to plot measurement 6, shot 1, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 19:05:14 MainThread analysis WARNING Exception trying to plot measurement 6, shot 2, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 19:05:15 MainThread analysis WARNING Exception trying to plot measurement 5, shot 2, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 19:05:16 MainThread analysis WARNING Exception trying to plot measurement 4, shot 2, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 19:05:25 MainThread analysis WARNING Exception trying to plot measurement 12, shot 0, in analysis.ShotsBrowserAnalysis.load()

2014/03/23 19:20:51 Thread-1 experiments ERROR Exception during experiment:
global name 'f' is not defined
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 393, in go2
    self.postExperiment()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 666, in postExperiment
    i.postExperiment(self.hdf5)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\analysis.py", line 99, in postExperiment
    self.analyzeExperiment(experimentResults)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\save2013style.py", line 82, in analyzeExperiment
    if 'iterations' in f:
NameError: global name 'f' is not defined


2014/03/23 19:20:51 Thread-1 experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 19:23:47 MainThread __main__ INFO starting application
2014/03/23 19:24:12 Thread-1 experiments DEBUG Autosaving
2014/03/23 19:24:12 Thread-1 experiments DEBUG Done autosaving
2014/03/23 19:24:12 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 19:24:12 Thread-1 experiments DEBUG Autosave closed
2014/03/23 19:24:12 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 19:24:14 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 19:24:14 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 19:24:19 Thread-1 experiments ERROR Exception during experiment:
global name 'array' is not defined
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 393, in go2
    self.postExperiment()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 666, in postExperiment
    i.postExperiment(self.hdf5)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\analysis.py", line 99, in postExperiment
    self.analyzeExperiment(experimentResults)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\save2013style.py", line 89, in analyzeExperiment
    sumarray=array(sumlist)
NameError: global name 'array' is not defined


2014/03/23 19:24:19 Thread-1 experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 19:26:31 MainThread __main__ INFO starting application
2014/03/23 19:26:54 Thread-1 experiments DEBUG Autosaving
2014/03/23 19:26:54 Thread-1 experiments DEBUG Done autosaving
2014/03/23 19:26:54 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 19:26:54 Thread-1 experiments DEBUG Autosave closed
2014/03/23 19:26:54 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 19:26:56 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 19:26:56 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 19:27:01 Thread-1 experiments ERROR Exception during experiment:
[Errno 2] No such file or directory: 'images\\average_of_all_images_in_experiment.png'
Traceback (most recent call last):
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 393, in go2
    self.postExperiment()
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\experiments.py", line 666, in postExperiment
    i.postExperiment(self.hdf5)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\analysis.py", line 99, in postExperiment
    self.analyzeExperiment(experimentResults)
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\save2013style.py", line 91, in analyzeExperiment
    self.savePNG(average_of_images,os.path.join('images','average_of_all_images_in_experiment.png'))
  File "C:\Users\Saffmanlab\Documents\git\CsPyController\python\save2013style.py", line 108, in savePNG
    png.from_array(array,'L;16',info={'bitdepth':16}).save(filename)
  File "C:\Users\Saffmanlab\AppData\Local\Enthought\Canopy\User\lib\site-packages\png.py", line 1301, in save
    file = open(file, 'wb')
IOError: [Errno 2] No such file or directory: 'images\\average_of_all_images_in_experiment.png'


2014/03/23 19:27:01 Thread-1 experiments WARNING Index=1 out of range for independent variable a. Setting a.index=0

2014/03/23 19:30:33 MainThread __main__ INFO starting application
2014/03/23 19:30:46 Thread-1 experiments DEBUG Autosaving
2014/03/23 19:30:46 Thread-1 experiments DEBUG Done autosaving
2014/03/23 19:30:46 Thread-1 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 19:30:46 Thread-1 experiments DEBUG Autosave closed
2014/03/23 19:30:46 Thread-1 experiments DEBUG Finished create_data_files()
2014/03/23 19:30:49 Thread-1 LabView DEBUG LabView.open() opening sock
2014/03/23 19:30:49 Thread-1 LabView DEBUG LabView.open() sock opened
2014/03/23 19:30:53 Thread-1 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
2014/03/23 19:33:52 Thread-2 experiments DEBUG Autosaving
2014/03/23 19:33:52 Thread-2 experiments DEBUG Done autosaving
2014/03/23 19:33:52 Thread-2 experiments DEBUG Copying autosave data to current HDF5
2014/03/23 19:33:52 Thread-2 experiments DEBUG Autosave closed
2014/03/23 19:33:52 Thread-2 experiments DEBUG Finished create_data_files()
2014/03/23 19:49:47 Thread-2 experiments INFO Current status is idle. Cannot continue an experiment unless status is paused.
